--- 
title: "Data Analysis in R & RStudio"
author: "Reka Solymosi and Eon Kim (based on material developed with Juanjo Medina)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
description: "This is the course material for Data Analysis in R & RStudio."
---

# Preface {-}

This is the main text you will be using during the labs for the module *Data Analysis in R & Studio* from Week 1 to Week 4. Every week you will have to use these materials during the lab sessions. The idea is that you read this lab note and try to run the code we provide in your own machine. Try not to just 'copy and paste' the codes in the lab note. Try to understand them. Along the way you will see you have to complete a series of exercises to check that you are correctly understanding the materials that we introduce. We hope you find these materials useful. This lab note is a work in process, so if you have any suggestions/find some errors, please don't hesitate to get in touch by submitting an issue to the [GitHub repository](https://github.com/eonk/dar_book) or via email on eon.kim@manchester.ac.uk.