<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter9 Regression in the real world | Data Analysis in Crime Science</title>
  <meta name="description" content="This is a study material for Criminology students at the University of Manchester." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter9 Regression in the real world | Data Analysis in Crime Science" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a study material for Criminology students at the University of Manchester." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter9 Regression in the real world | Data Analysis in Crime Science" />
  
  <meta name="twitter:description" content="This is a study material for Criminology students at the University of Manchester." />
  

<meta name="author" content="" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="an-introduction-to-regression.html"/>
<link rel="next" href="logistic-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Analysis in Crime Science</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#functions-talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Functions: Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#objects-creating-an-object"><i class="fa fa-check"></i><b>1.7</b> Objects: creating an object</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.9</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#r-object-types-vectors"><i class="fa fa-check"></i><b>1.10</b> R object types: vectors</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#r-object-types-data-frame"><i class="fa fa-check"></i><b>1.11</b> R object types: Data frame</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#exploring-data"><i class="fa fa-check"></i><b>1.12</b> Exploring data</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#r-data-types-factors"><i class="fa fa-check"></i><b>1.13</b> R data types: Factors</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#how-to-import-data"><i class="fa fa-check"></i><b>1.14</b> How to import data</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#how-to-use-comment"><i class="fa fa-check"></i><b>1.15</b> How to use ‘comment’</a></li>
<li class="chapter" data-level="1.16" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#how-to-quit-rstudio"><i class="fa fa-check"></i><b>1.16</b> How to Quit RStudio</a></li>
<li class="chapter" data-level="1.17" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#summary-exercise-for-this-week"><i class="fa fa-check"></i><b>1.17</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html"><i class="fa fa-check"></i><b>2</b> Getting to know your data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#causality-in-social-sciences"><i class="fa fa-check"></i><b>2.1</b> Causality in social sciences</a></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#getting-data-thanks-to-reproducibility"><i class="fa fa-check"></i><b>2.2</b> Getting data thanks to reproducibility</a></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#getting-a-sense-for-your-data"><i class="fa fa-check"></i><b>2.3</b> Getting a sense for your data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#first-steps"><i class="fa fa-check"></i><b>2.3.1</b> First steps</a></li>
<li class="chapter" data-level="2.3.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#on-tibbles-and-labelled-vectors"><i class="fa fa-check"></i><b>2.3.2</b> On tibbles and labelled vectors</a></li>
<li class="chapter" data-level="2.3.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#turning-variables-into-factors-and-changing-the-labels"><i class="fa fa-check"></i><b>2.3.3</b> Turning variables into factors and changing the labels</a></li>
<li class="chapter" data-level="2.3.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#looking-for-missing-data-and-other-anomalies"><i class="fa fa-check"></i><b>2.3.4</b> Looking for missing data and other anomalies</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.4</b> Data wrangling with dplyr</a></li>
<li class="chapter" data-level="2.5" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#using-dplyr-single-verbs"><i class="fa fa-check"></i><b>2.5</b> Using dplyr single verbs</a></li>
<li class="chapter" data-level="2.6" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#using-dplyr-for-grouped-operations"><i class="fa fa-check"></i><b>2.6</b> Using dplyr for grouped operations</a></li>
<li class="chapter" data-level="2.7" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#making-comparisons-with-numerical-outcomes"><i class="fa fa-check"></i><b>2.7</b> Making comparisons with numerical outcomes</a></li>
<li class="chapter" data-level="2.8" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#summary-exercise-for-this-week-1"><i class="fa fa-check"></i><b>2.8</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html"><i class="fa fa-check"></i><b>3</b> Data visualisation with R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#anatomy-of-a-plot"><i class="fa fa-check"></i><b>3.2</b> Anatomy of a plot</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#what-graph-should-i-use"><i class="fa fa-check"></i><b>3.3</b> What graph should I use?</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-histograms"><i class="fa fa-check"></i><b>3.4</b> Visualising numerical variables: Histograms</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-density-plots"><i class="fa fa-check"></i><b>3.5</b> Visualising numerical variables: Density plots</a></li>
<li class="chapter" data-level="3.6" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-box-plots"><i class="fa fa-check"></i><b>3.6</b> Visualising numerical variables: Box plots</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#exploring-relationships-between-two-quantitative-variables-scatterplots"><i class="fa fa-check"></i><b>3.7</b> Exploring relationships between two quantitative variables: scatterplots</a></li>
<li class="chapter" data-level="3.8" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplots-conditioning-in-a-third-variable"><i class="fa fa-check"></i><b>3.8</b> Scatterplots conditioning in a third variable</a></li>
<li class="chapter" data-level="3.9" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplot-matrix"><i class="fa fa-check"></i><b>3.9</b> Scatterplot matrix</a></li>
<li class="chapter" data-level="3.10" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#titles-legends-and-themes-in-ggplot2"><i class="fa fa-check"></i><b>3.10</b> Titles, legends, and themes in ggplot2</a></li>
<li class="chapter" data-level="3.11" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#plotting-categorical-data-bar-charts"><i class="fa fa-check"></i><b>3.11</b> Plotting categorical data: bar charts</a></li>
<li class="chapter" data-level="3.12" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#further-resources"><i class="fa fa-check"></i><b>3.12</b> Further resources</a></li>
<li class="chapter" data-level="3.13" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#summary-exercise-for-this-week-2"><i class="fa fa-check"></i><b>3.13</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html"><i class="fa fa-check"></i><b>4</b> Refresher on descriptive statistics &amp; data carpentry</a>
<ul>
<li class="chapter" data-level="4.1" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#getting-some-data-from-eurobarometer"><i class="fa fa-check"></i><b>4.2</b> Getting some data from Eurobarometer</a></li>
<li class="chapter" data-level="4.3" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#thinking-about-your-data-filtering-cases"><i class="fa fa-check"></i><b>4.3</b> Thinking about your data: filtering cases</a></li>
<li class="chapter" data-level="4.4" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#selecting-variables-using-dplyrselect"><i class="fa fa-check"></i><b>4.4</b> Selecting variables: using <code>dplyr::select</code></a></li>
<li class="chapter" data-level="4.5" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#creating-summated-scales"><i class="fa fa-check"></i><b>4.5</b> Creating summated scales</a></li>
<li class="chapter" data-level="4.6" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#collapsing-categories-in-character-variables"><i class="fa fa-check"></i><b>4.6</b> Collapsing categories in character variables</a></li>
<li class="chapter" data-level="4.7" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#working-with-apparently-cryptic-variable-names-and-levels"><i class="fa fa-check"></i><b>4.7</b> Working with apparently cryptic variable names and levels</a></li>
<li class="chapter" data-level="4.8" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#recoding-factors"><i class="fa fa-check"></i><b>4.8</b> Recoding factors</a></li>
<li class="chapter" data-level="4.9" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#understanding-missing-data"><i class="fa fa-check"></i><b>4.9</b> Understanding missing data</a></li>
<li class="chapter" data-level="4.10" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#exploring-dataframes-visually"><i class="fa fa-check"></i><b>4.10</b> Exploring dataframes visually</a></li>
<li class="chapter" data-level="4.11" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#a-quick-recap-on-descriptive-statistics"><i class="fa fa-check"></i><b>4.11</b> A quick recap on descriptive statistics</a>
<ul>
<li class="chapter" data-level="4.11.1" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#central-tendency"><i class="fa fa-check"></i><b>4.11.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.11.2" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#dispersion"><i class="fa fa-check"></i><b>4.11.2</b> Dispersion</a></li>
<li class="chapter" data-level="4.11.3" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#bivariate-analysis"><i class="fa fa-check"></i><b>4.11.3</b> Bivariate analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#further-resources-1"><i class="fa fa-check"></i><b>4.12</b> Further resources</a></li>
<li class="chapter" data-level="4.13" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#summary-exercise-for-this-week-3"><i class="fa fa-check"></i><b>4.13</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Foundations of statistical inference: confidence intervals</a>
<ul>
<li class="chapter" data-level="5.1" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#generating-random-data"><i class="fa fa-check"></i><b>5.2</b> Generating random data</a></li>
<li class="chapter" data-level="5.3" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#sampling-data-and-sampling-variability"><i class="fa fa-check"></i><b>5.3</b> Sampling data and sampling variability</a></li>
<li class="chapter" data-level="5.4" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#sampling-distributions-and-sampling-experiments"><i class="fa fa-check"></i><b>5.4</b> Sampling distributions and sampling experiments</a></li>
<li class="chapter" data-level="5.5" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#the-normal-distribution-and-confidence-intervals-with-known-standard-errors"><i class="fa fa-check"></i><b>5.5</b> The normal distribution and confidence intervals with known standard errors</a></li>
<li class="chapter" data-level="5.6" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#asymptotic-confidence-intervals-for-means-and-proportions-using-r"><i class="fa fa-check"></i><b>5.6</b> Asymptotic confidence intervals for means and proportions using R</a></li>
<li class="chapter" data-level="5.7" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#a-brief-intro-to-resampling-and-bootstraping"><i class="fa fa-check"></i><b>5.7</b> A brief intro to resampling and bootstraping</a></li>
<li class="chapter" data-level="5.8" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#what-about-comparisons-sampling-distribution-for-the-difference-of-two-means"><i class="fa fa-check"></i><b>5.8</b> What about comparisons? Sampling distribution for the difference of two means</a></li>
<li class="chapter" data-level="5.9" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#comparing-means-visually-by-using-error-bars-representing-confidence-intervals-inference-by-eye"><i class="fa fa-check"></i><b>5.9</b> Comparing means visually by using error bars representing confidence intervals: inference by eye</a></li>
<li class="chapter" data-level="5.10" data-path="foundations-of-statistical-inference-confidence-intervals.html"><a href="foundations-of-statistical-inference-confidence-intervals.html#summary-exercise-for-this-week-4"><i class="fa fa-check"></i><b>5.10</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>6</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hypotheses.html"><a href="hypotheses.html#the-logic-of-hypothesis-testing"><i class="fa fa-check"></i><b>6.1</b> The logic of hypothesis testing</a></li>
<li class="chapter" data-level="6.2" data-path="hypotheses.html"><a href="hypotheses.html#comparing-means-across-two-groups-the-t-test"><i class="fa fa-check"></i><b>6.2</b> Comparing means across two groups (the t test)</a></li>
<li class="chapter" data-level="6.3" data-path="hypotheses.html"><a href="hypotheses.html#what-does-a-significant-effect-mean"><i class="fa fa-check"></i><b>6.3</b> What does a significant effect mean?</a></li>
<li class="chapter" data-level="6.4" data-path="hypotheses.html"><a href="hypotheses.html#power-analysis"><i class="fa fa-check"></i><b>6.4</b> Power analysis</a></li>
<li class="chapter" data-level="6.5" data-path="hypotheses.html"><a href="hypotheses.html#comparing-means-across-several-groups-anova"><i class="fa fa-check"></i><b>6.5</b> Comparing means across several groups (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="hypotheses.html"><a href="hypotheses.html#the-problem-with-multiple-comparisons"><i class="fa fa-check"></i><b>6.5.1</b> The problem with multiple comparisons</a></li>
<li class="chapter" data-level="6.5.2" data-path="hypotheses.html"><a href="hypotheses.html#visual-exploration-of-differences-in-the-distributions-across-the-groups"><i class="fa fa-check"></i><b>6.5.2</b> Visual exploration of differences in the distributions across the groups</a></li>
<li class="chapter" data-level="6.5.3" data-path="hypotheses.html"><a href="hypotheses.html#anova"><i class="fa fa-check"></i><b>6.5.3</b> ANOVA</a></li>
<li class="chapter" data-level="6.5.4" data-path="hypotheses.html"><a href="hypotheses.html#checking-homogeneity-of-variance-and-dealing-with-unequal-spread"><i class="fa fa-check"></i><b>6.5.4</b> Checking homogeneity of variance and dealing with unequal spread</a></li>
<li class="chapter" data-level="6.5.5" data-path="hypotheses.html"><a href="hypotheses.html#checking-normality-and-dealing-with-problems"><i class="fa fa-check"></i><b>6.5.5</b> Checking normality and dealing with problems</a></li>
<li class="chapter" data-level="6.5.6" data-path="hypotheses.html"><a href="hypotheses.html#robust-anova"><i class="fa fa-check"></i><b>6.5.6</b> Robust ANOVA</a></li>
<li class="chapter" data-level="6.5.7" data-path="hypotheses.html"><a href="hypotheses.html#post-hoc-comparisons"><i class="fa fa-check"></i><b>6.5.7</b> Post Hoc Comparisons</a></li>
<li class="chapter" data-level="6.5.8" data-path="hypotheses.html"><a href="hypotheses.html#effect-size-for-anova"><i class="fa fa-check"></i><b>6.5.8</b> Effect size for ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="hypotheses.html"><a href="hypotheses.html#summary-exercise-for-this-week-5"><i class="fa fa-check"></i><b>6.6</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html"><i class="fa fa-check"></i><b>7</b> Studying relationships between two factors</a>
<ul>
<li class="chapter" data-level="7.1" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#producing-cross-tabulations"><i class="fa fa-check"></i><b>7.1</b> Producing cross tabulations</a></li>
<li class="chapter" data-level="7.2" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#expected-frequencies-and-chi-square"><i class="fa fa-check"></i><b>7.2</b> Expected frequencies and Chi-Square</a></li>
<li class="chapter" data-level="7.3" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#residuals"><i class="fa fa-check"></i><b>7.3</b> Residuals</a></li>
<li class="chapter" data-level="7.4" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#gamma"><i class="fa fa-check"></i><b>7.4</b> Gamma</a></li>
<li class="chapter" data-level="7.5" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#odds-and-odd-ratios"><i class="fa fa-check"></i><b>7.5</b> Odds and odd ratios</a></li>
<li class="chapter" data-level="7.6" data-path="studying-relationships-between-two-factors.html"><a href="studying-relationships-between-two-factors.html#summary-exercise-for-this-week-6"><i class="fa fa-check"></i><b>7.6</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html"><i class="fa fa-check"></i><b>8</b> An introduction to regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#introduction-models-in-scientific-research"><i class="fa fa-check"></i><b>8.1</b> Introduction: models in scientific research</a></li>
<li class="chapter" data-level="8.2" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#motivating-regression"><i class="fa fa-check"></i><b>8.2</b> Motivating regression</a></li>
<li class="chapter" data-level="8.3" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>8.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="8.4" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#residuals-revisited-r-squared"><i class="fa fa-check"></i><b>8.4</b> Residuals revisited: R squared</a></li>
<li class="chapter" data-level="8.5" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#inference-with-regression"><i class="fa fa-check"></i><b>8.5</b> Inference with regression</a></li>
<li class="chapter" data-level="8.6" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>8.6</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="8.7" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>8.7</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="8.8" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>8.8</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="8.9" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#presenting-your-regression-results."><i class="fa fa-check"></i><b>8.9</b> Presenting your regression results.</a></li>
<li class="chapter" data-level="8.10" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#rescaling-input-variables-to-assist-interpretation"><i class="fa fa-check"></i><b>8.10</b> Rescaling input variables to assist interpretation</a></li>
<li class="chapter" data-level="8.11" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>8.11</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="8.12" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#regression-assumptions"><i class="fa fa-check"></i><b>8.12</b> Regression assumptions</a></li>
<li class="chapter" data-level="8.13" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#model-building-and-variable-selection"><i class="fa fa-check"></i><b>8.13</b> Model building and variable selection</a></li>
<li class="chapter" data-level="8.14" data-path="an-introduction-to-regression.html"><a href="an-introduction-to-regression.html#summary-exercise-for-this-week-7"><i class="fa fa-check"></i><b>8.14</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html"><i class="fa fa-check"></i><b>9</b> Regression in the real world</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#introduction-3"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#plotting-residuals"><i class="fa fa-check"></i><b>9.2</b> Plotting residuals</a></li>
<li class="chapter" data-level="9.3" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#checking-for-normality-outliers-and-influential-data"><i class="fa fa-check"></i><b>9.3</b> Checking for normality, outliers and influential data</a></li>
<li class="chapter" data-level="9.4" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#dealing-with-non-linearities-and-unequal-variances"><i class="fa fa-check"></i><b>9.4</b> Dealing with non linearities (and unequal variances)</a></li>
<li class="chapter" data-level="9.5" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#transformations-and-unequal-variance"><i class="fa fa-check"></i><b>9.5</b> Transformations and unequal variance</a></li>
<li class="chapter" data-level="9.6" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#boostrapping-regression-models"><i class="fa fa-check"></i><b>9.6</b> Boostrapping regression models</a></li>
<li class="chapter" data-level="9.7" data-path="regression-in-the-real-world.html"><a href="regression-in-the-real-world.html#multicollinearity"><i class="fa fa-check"></i><b>9.7</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>10</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="logistic-regression.html"><a href="logistic-regression.html#introduction-4"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-logistic-regression"><i class="fa fa-check"></i><b>10.2</b> Fitting logistic regression</a></li>
<li class="chapter" data-level="10.3" data-path="logistic-regression.html"><a href="logistic-regression.html#assessing-model-fit-i-deviance-and-pseudo-r-squared"><i class="fa fa-check"></i><b>10.3</b> Assessing model fit I: deviance and pseudo r squared</a></li>
<li class="chapter" data-level="10.4" data-path="logistic-regression.html"><a href="logistic-regression.html#assessing-model-fit-ii-confusion-matrix-and-roc-curves"><i class="fa fa-check"></i><b>10.4</b> Assessing model fit II: confusion matrix and ROC curves</a></li>
<li class="chapter" data-level="10.5" data-path="logistic-regression.html"><a href="logistic-regression.html#interactions"><i class="fa fa-check"></i><b>10.5</b> Interactions</a></li>
<li class="chapter" data-level="10.6" data-path="logistic-regression.html"><a href="logistic-regression.html#further-resources-2"><i class="fa fa-check"></i><b>10.6</b> Further resources</a></li>
<li class="chapter" data-level="10.7" data-path="logistic-regression.html"><a href="logistic-regression.html#summary-exercise-for-this-week-8"><i class="fa fa-check"></i><b>10.7</b> Summary: exercise for this week</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="wrapping-up.html"><a href="wrapping-up.html"><i class="fa fa-check"></i><b>11</b> Wrapping up</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis in Crime Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-in-the-real-world" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter9</span> Regression in the real world<a href="regression-in-the-real-world.html#regression-in-the-real-world" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="introduction-3" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Introduction<a href="regression-in-the-real-world.html#introduction-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Although so far we have discussed the practicalities of fitting and interpreting regression models, in practical applications you want to first check your model and proceed from there. Not much point spending time interpreting your model until you know that the model reasonably fits your data.</p>
<p>In previous sessions we talked about the assumptions made by various statistical tests. The regression model also makes assumptions of its own. In fact, there are so many that we will spend an entire session discussing them. We follow for the most part Gelman and Hill (2007) discussion of these assumptions. These authors point out that the most important assumptions by decreasing order of importance are:</p>
<ul>
<li><strong>Validity</strong>. The data should be appropriate for the question that you are trying to answer:</li>
</ul>
<blockquote>
<p>“Optimally, this means that the outcome measure should accurately reflect the phenomenon of interes, the model should include all relevant predictors, and the model should generalize to all cases to which it will be applied… Data used in empirical research rarely meet all (if any) of these criteria precisely. However, keeping these goals in mind can help you be precise about the types of questions you can and cannot answer reliably”</p>
</blockquote>
<ul>
<li><p><strong>Additiviy and linearity</strong>. These are the most important mathematical assumptions of the model. We already talked about additivity in previous sessions and discussed how you can include interaction effects in your models if the additivity assumption is violated. We will discuss problems with non-linearities today as well as ways to diagnose and solve this problem. If the relationship is non linear (e.g, it is curvilinear) predicted values will be wrong in a biased manner, meaning that predicted values will systematically miss the true pattern of the mean of y (as related to the x-variables).</p></li>
<li><p><strong>Independence of errors</strong>. Regression assumes that the errors from the prediciton line (or hyperplane) are independent. If there is dependency between the observations (you are assessing change across the same units, working with spatial units, or with units that are somehowed grouped such as students from the same class), you may have to use models that are more appropriate (e.g., multilevel models, spatial regression, etc.).</p></li>
<li><p><strong>Equal variances of errors</strong>. When the variance of the residuals is unequal, you may need different estimation methods. This is, nonetheless, considered a minor issue. There is a small effect on the validity of t-test and F-test results, but generally regression inferences are robust with regard to the variance issue.</p></li>
<li><p><strong>Normality of errors</strong>. The residuals should be normally distributed. Gelman and Hill (2007: 46) discuss this as the least important of the assumptions and in fact “do <em>not</em> recommend diagnostics of the normality of the regression residuals”. If the errors do not have a normal distribution, it usually is not particularly serious. Regression inferences tend to be robust with respect to normality (or nonnormality of the errors). In practice, the residuals may appear to be nonnormal when the wrong regression equation has been used. So, I will show you how to inspect normality of the residuals not because this is a problem on itself, but because it may be give you further evidence that there is some other problem with the model you are applying to your data.</p></li>
</ul>
<p>Apart from this, it is convenient to diagnose multicollinearity (this affects interpretation) and influential observations.</p>
<p>So these are the assumptions of linear regression, and today we will go through how to test for them, and also what are some options that you can consider if you find that your model violates them. While finding that some of the assumptions are violated do not necessarily mean that you have to scrap your model, it is important to use these diagnostics to illustrate that you have considered what the possible issues with your model is, and if you find any serious issues that you address them.</p>
<p>We’ll be using the British Crime Survey daya from 2007/8 again, so read it in (you might already have it saved from earlier sessions):</p>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="regression-in-the-real-world.html#cb612-1" tabindex="-1"></a><span class="do">##R in Windows have some problems with https addresses, that&#39;s why we need to do this first:</span></span>
<span id="cb612-2"><a href="regression-in-the-real-world.html#cb612-2" tabindex="-1"></a>BCS0708<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/eonk/dar_book/main/datasets/BCS0708.csv&quot;</span>)</span></code></pre></div>
</div>
<div id="plotting-residuals" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Plotting residuals<a href="regression-in-the-real-world.html#plotting-residuals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Many of the assumptions can be tested first by having a look at your residuals. Remember, the residuals are the ‘error’ in your model. In previous weeks we defined the ordinary residuals as the difference between the observed and the predicted values, the distance between the points in your scatterplot and the regression line. Apart from the ordinary residuals, most software computes other forms of closely related ones: the standardised, the studentised, and the Pearson residuals.</p>
<p>The raw residuals are just the difference between the observed and the predicted, the other three are ways of normalising this measure, so you can compare what is large, what is small, etc. For example, with the standardized residuals, you essentailly calculate z scores, and given a normal distribution of the standardized residuals, the mean is 0, and the standard deviations is 1.
Pearson residuas are raw residuals divided by the standard error of the observed value.
Studentized resiruals (also called standardized pearson residuals) are raw residuals divided by their standard error.
You can read more about these <a href="https://r-forge.r-project.org/scm/viewvc.php/*checkout*/pkg/BinomTools/inst/ResidualsGLM.pdf?revision=6&amp;root=binomtools&amp;pathrev=6">here</a>.</p>
<p>Plotting these residuals versus the fitted values and versus each of the predictors is the most basic way of diagnosing problems with your regression model. However, as Fox and Weisberg (2011) emphasise
&gt; this “is useful for revealing problems but less useful for determining the exact nature of the problem” and consequently one needs “other diagnostic graphs to suggest improvements to the model”.</p>
<p>In the previous session we fitted the model <code>tcviolent ~ tcarea + sex</code>. This was our <code>fit_3</code> model during that session. You may have to run the model again if you do not have it in your global environment.</p>
<p>To obtain the basic residual plots for this model we use the <code>residualPlots()</code> function of the <code>car</code> package.</p>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="regression-in-the-real-world.html#cb613-1" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="regression-in-the-real-world.html#cb615-1" tabindex="-1"></a>fit_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tcviolent <span class="sc">~</span> tcarea <span class="sc">+</span> sex, <span class="at">data=</span>BCS0708)</span>
<span id="cb615-2"><a href="regression-in-the-real-world.html#cb615-2" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_3)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)    
## tcarea        6.2571        4.123e-10 ***
## sex                                      
## Tukey test    4.6065        4.094e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This function will produce plots of the Pearson residuals versus each of the predictors in the model and versus the fitted values.</p>
<div id="residuals-vs-predicted-values" class="section level4 hasAnchor" number="9.2.0.1">
<h4><span class="header-section-number">9.2.0.1</span> Residuals vs predicted values<a href="regression-in-the-real-world.html#residuals-vs-predicted-values" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The most important of this is the last one, <em>the scatterplot of the Pearson residuals versus the fitted values</em>. In these plots one has to pay particular attention to nonlinear trends, trends in variations across the graph, but also isolated points.
Ideally a plot of the residuals should show that:</p>
<ul>
<li>they’re pretty symmetrically distributed, tending to cluster towards the middle of the plot</li>
<li>they’re clustered around the lower single digits of the y-axis (e.g., 0.5 or 1.5, not 30 or 150)</li>
<li>in general there aren’t clear patterns</li>
</ul>
<p>For example this is a good looking scatterplot of residuals vs fitted values:</p>
<p><img src="imgs/respre.png" /></p>
<p>On the other hand, if your plot isn’t evenly distributed vertically, or they have an outlier, or they have a clear shape to them, that indicates you can detect a clear pattern or trend in your residuals. In this case, then your model has room for improvement.</p>
<p>For example, these are scatterplots of residuals vs fitted values that indicate a problem:
<img src="imgs/respre2.png" />
<img src="imgs/respre3.png" />
<img src="imgs/respre4.png" />
<img src="imgs/respre5.png" /></p>
<p>How concerned should you be if your model isn’t perfect, if your residuals look a bit unhealthy? It’s up to you. Most of the time a decent model is better than none at all. So take your model, try to improve it, and then decide whether the accuracy is good enough to be useful for your purposes.</p>
</div>
<div id="residuals-vs-predictors" class="section level4 hasAnchor" number="9.2.0.2">
<h4><span class="header-section-number">9.2.0.2</span> Residuals vs predictors<a href="regression-in-the-real-world.html#residuals-vs-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>These plots are related to the <strong>homogeneity of variance</strong> assumption we introduced earlier.</p>
<p>When the predictor is <strong>categorical</strong>, we will see a collection of boxplots (one for each level in the predictor). A good fit will be indicated by boxplots that have the same centre and similar spread.</p>
<p>When the predictor is <strong>numeric</strong>, we see a scatterplot of the predictor against the Pearson residuals. Here we also look at any systematic differences in the spread of the residuals across the X axis. When the variances are not unequal you can often see a funnel form shaping up, with less variance at one end of the X axis than the other. Though other systematic patterns are also possible. You also need to pay attention to the shape of the red line printed in the output. This line should be straight. If you observe non-linearities (e.g., a curved line), this may be a more serious issue than the unequal spread and will need addressing.</p>
</div>
<div id="diagnostic" class="section level4 hasAnchor" number="9.2.0.3">
<h4><span class="header-section-number">9.2.0.3</span> Diagnostic<a href="regression-in-the-real-world.html#diagnostic" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When you run the <code>residualPlots()</code> function R will also print two numerical tests.</p>
<p>First we have a curvature test for each of the plots by adding a quadratic term and testing the quadratic to be zero (more on this in a few sections). This is Tukey’s test for nonadditivity when plotting against fitted values. When this test is significant it may indicate a <strong>lack of fit</strong> for this particular predictor.</p>
<p>The Tukey test optimally should not be significant. We can see in the first of the three plots that the red line is a bit curved. It is this pattern that the printed tests are picking up.</p>
</div>
<div id="marginal-plots" class="section level4 hasAnchor" number="9.2.0.4">
<h4><span class="header-section-number">9.2.0.4</span> Marginal plots<a href="regression-in-the-real-world.html#marginal-plots" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can further diagnose the model by printing <strong>marginal model plots</strong> using the <code>marginalModelPlots()</code> function of the <code>car</code> package.</p>
<pre><code>## Error in plot.window(...): need finite &#39;xlim&#39; values</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>This will plot a scatterplot for each predictor variable against the response variable. This displays the conditional distribution of the response given each predictor, <em>ignoring the other predictors</em>. They are called marginal plots because they show the marginal relationship between the outcome and <em>each predictor</em>. It will also print a scatterplot of the response versus the fitted value displaying the conditional distribution of the outcome given the fit of the model. We observe here the curvature that was already identified by the previous plots (notice the blue line).</p>
<p>We can also use the <code>marginalModelPlots()</code> function to assess the <strong>homogeneity of variance</strong> assumption using the following argument:</p>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="regression-in-the-real-world.html#cb618-1" tabindex="-1"></a><span class="fu">marginalModelPlots</span>(fit_3, <span class="at">sd =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in xy.coords(x, y, xlabel, ylabel, log): NAs introduced by coercion</code></pre>
<pre><code>## Warning in min(x): no non-missing arguments to min; returning Inf</code></pre>
<pre><code>## Warning in max(x): no non-missing arguments to max; returning -Inf</code></pre>
<pre><code>## Error in plot.window(...): need finite &#39;xlim&#39; values</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>This will print the estimated standard deviation lines to the graph. You would want this to be <strong>constant</strong> across the X axis.</p>
</div>
<div id="diagnostic-for-homoskedasiticity" class="section level4 hasAnchor" number="9.2.0.5">
<h4><span class="header-section-number">9.2.0.5</span> Diagnostic for homoskedasiticity<a href="regression-in-the-real-world.html#diagnostic-for-homoskedasiticity" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>And since we are discussing homoskedasiticity (e.g., homogeneity of variance or constant/equal variance), it is worth pointing out that the <code>car</code> package implements a score test that evaluates whether the variance is constant. To obtain this test we use the <code>ncvTest()</code> function.</p>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="regression-in-the-real-world.html#cb623-1" tabindex="-1"></a><span class="fu">ncvTest</span>(fit_3)</span></code></pre></div>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 186.8947, Df = 1, p = &lt; 2.22e-16</code></pre>
<p>When the test is <strong>significant</strong>, as it is here, we may suspect there <strong>is</strong> a problem with non-constant variance (also called heterokedasticity). In practice, should already be visible from the plot of residuals versus fits plot.</p>
</div>
</div>
<div id="checking-for-normality-outliers-and-influential-data" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Checking for normality, outliers and influential data<a href="regression-in-the-real-world.html#checking-for-normality-outliers-and-influential-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we said regression is quite robust to the non-normality of the errors, but it may be helpful to check it as a way to reinfore our overall assessment of the fit of the model. Typically, non-normal errors may be indicating that other (more serious) problems are present. You should look at these diagnostics in conjunction with all the others we have covered so far.</p>
<p>We are also interested in assessing the impact that extreme observations (<em>outliers</em>) may have in our results. There are different types of outliers. We are particularly concerned with those that will significantly affect our substantive conclusions (referred to as <strong>influential observations</strong>). Just keep in mind that outliers may be interesting in their own right and not necessarily bad data. Check <a href="http://stattrek.com/regression/influential-points.aspx">this explanation</a> of the various types of outliers you may encounter in regression before you proceed. You will see the “stattrek” site discusses outliers regarding X, in regression you typically are only concerned with outliers regarding Y. <a href="https://onlinecourses.science.psu.edu/stat501/node/337">Here</a> you can find a fuller explanation that I strongly recommend you read in order to more fully understand these concepts.</p>
<div id="density-estimate-of-the-residuals" class="section level4 hasAnchor" number="9.3.0.1">
<h4><span class="header-section-number">9.3.0.1</span> Density estimate of the residuals<a href="regression-in-the-real-world.html#density-estimate-of-the-residuals" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We could plot the density estimate of the residuals:</p>
<div class="sourceCode" id="cb625"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb625-1"><a href="regression-in-the-real-world.html#cb625-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(<span class="fu">rstudent</span>(fit_3)))</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>We can see that the right hand side tail is heavier than it should be.</p>
</div>
<div id="qqplot" class="section level4 hasAnchor" number="9.3.0.2">
<h4><span class="header-section-number">9.3.0.2</span> qqplot<a href="regression-in-the-real-world.html#qqplot" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We could also use a normal probability plot to assess the normality of the residuals using the <code>qqPlot()</code> function of the <code>car</code> package;</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="regression-in-the-real-world.html#cb626-1" tabindex="-1"></a><span class="fu">qqPlot</span>(fit_3, <span class="at">id.n =</span> <span class="dv">3</span>) <span class="co">#The id.n argument asks R to identify the row number for the most extreme observations, the value specifies how many cases we want to higlight</span></span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre><code>## [1] 1761 3919</code></pre>
<p>You have a few cases where the fitted values are much smaller than the observed values (thus the large positive residuals) particularly in the right hand side of the plot. As we saw in previous residual plots, there is a bit curvature in the data. It is likely this may be what this plot is picking up here.</p>
</div>
<div id="outliers" class="section level4 hasAnchor" number="9.3.0.3">
<h4><span class="header-section-number">9.3.0.3</span> Outliers<a href="regression-in-the-real-world.html#outliers" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can also run a formal test for outliers using the following function from the <code>car</code> package. This function locates the largest Studentised residuals in absolute value and computes a Bonferroni-corrected t test. If the probability value associated with this test is smaller than your alpha value, then you can conclude the observation you are dealing with is likely an outlier. Look at our results from using the function, what can you conclude?</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="regression-in-the-real-world.html#cb628-1" tabindex="-1"></a><span class="fu">outlierTest</span>(fit_3)</span></code></pre></div>
<pre><code>##      rstudent unadjusted p-value Bonferroni p
## 1761 4.746679         2.1037e-06     0.016855</code></pre>
</div>
<div id="influential-cases" class="section level4 hasAnchor" number="9.3.0.4">
<h4><span class="header-section-number">9.3.0.4</span> Influential cases<a href="regression-in-the-real-world.html#influential-cases" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>So far we have only been looking at outliers, but we can also obtain information about unusual cases that have large influence in our results (remember the distinction higlighted in the recommended reading material above). For identifying influential observations we can use visual methods. The <code>influencePlot()</code> function, also from the <code>car</code> package, produces a bubble plot, which combine measures of the residuals and other statistics (hat values and Cook distance) oriented to identify influential observations.</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="regression-in-the-real-world.html#cb630-1" tabindex="-1"></a><span class="fu">influencePlot</span>(fit_3, <span class="at">id.n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Warning in plot.window(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy, type, ...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not a
## graphical parameter

## Warning in axis(side = side, at = at, labels = labels, ...): &quot;id.n&quot; is not a
## graphical parameter</code></pre>
<pre><code>## Warning in box(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in title(...): &quot;id.n&quot; is not a graphical parameter</code></pre>
<pre><code>## Warning in plot.xy(xy.coords(x, y), type = type, ...): &quot;id.n&quot; is not a
## graphical parameter</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>##        StudRes          Hat        CookD
## 1761  4.746679 0.0003234944 0.0024238163
## 3027 -3.462209 0.0020643297 0.0082540371
## 3420  2.918465 0.0014178636 0.0040274579
## 3919  4.130348 0.0003178580 0.0018044856
## 5917  1.093652 0.0024393741 0.0009749124
## 9549  1.566849 0.0024995094 0.0020501974</code></pre>
<p>We should be concerned by cases that are outlying (have a large residual), those will have very or very low score in the Y axis, <em>and</em> have high leverage as indicated by their <em>hat value</em> (are relatively far from the center of the regressor space), those will have high scores in the Y axis.</p>
<p>The size of the bubble gives you the <em>Cook distance</em>, which is a statistic that tries to summarise how much your regression coefficients may change without that particular case. Here we see that our only significant outlier (as diagnosed by the statistical test we run earlier) has fairly low leverage. There are a number of observations with more than twice the mean hat value (the first dashed line in the x axis) and three times the mean hat value (the second dashed line in the x axis).</p>
<p>We can compare the two models using the following code:</p>
<div class="sourceCode" id="cb638"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb638-1"><a href="regression-in-the-real-world.html#cb638-1" tabindex="-1"></a><span class="co">#This will rerun regression but without the case 1761 in our dataset and store the results in a new object</span></span>
<span id="cb638-2"><a href="regression-in-the-real-world.html#cb638-2" tabindex="-1"></a>fit_3_no <span class="ot">&lt;-</span> <span class="fu">update</span>(fit_3, <span class="at">subset =</span> <span class="fu">rownames</span>(BCS0708) <span class="sc">!=</span> <span class="dv">1761</span>)</span>
<span id="cb638-3"><a href="regression-in-the-real-world.html#cb638-3" tabindex="-1"></a><span class="co">#The compareCoeff() function will print the coefficients for the two models and allow us to compare their magnitude and standard errors.</span></span>
<span id="cb638-4"><a href="regression-in-the-real-world.html#cb638-4" tabindex="-1"></a><span class="fu">compareCoefs</span>(fit_3, fit_3_no)</span></code></pre></div>
<pre><code>## Calls:
## 1: lm(formula = tcviolent ~ tcarea + sex, data = BCS0708)
## 2: lm(formula = tcviolent ~ tcarea + sex, data = BCS0708, subset = 
##   rownames(BCS0708) != 1761)
## 
##             Model 1 Model 2
## (Intercept)  0.3134  0.3134
## SE           0.0139  0.0139
##                            
## tcarea       0.3104  0.3108
## SE           0.0103  0.0103
##                            
## sexmale     -0.5968 -0.5979
## SE           0.0203  0.0202
## </code></pre>
<p>As you can see almost nothing changes. You should try to see what happens when you change the other two cases we have higlighted (the one with the largest leverage, 9549, and the one with the largest Cook Distance, 3027). If you were really concerned with influential observations you may want to consider some form of robust regression. For a tutorial on how to do this with R, check <a href="http://www.ats.ucla.edu/stat/r/dae/rreg.htm">here</a>.</p>
<p>It is important to realise that the absolute cutoffs discussed and the statistical tests mentioned for unusual data will often be more helpful with small datasets. With large samples absolute cutoffs for measures of influence are unlikely to identify noteworthy observations.</p>
</div>
</div>
<div id="dealing-with-non-linearities-and-unequal-variances" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Dealing with non linearities (and unequal variances)<a href="regression-in-the-real-world.html#dealing-with-non-linearities-and-unequal-variances" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The diagnostics we have carried out so far suggest that perhaps we had a problem with non-linearities regarding the relationship between fear of violent crime and perceptions of antisocial behaviour. The residual plots seem to indicate that the model we fitted underpredict at low and high levels of perceptions of antisocial behaviour. Let’s look back at the marginal relationship between these two variables through a scatterplot.</p>
<p>As we said one of the fundamental assumptions of regression is that the model assumes that a straight line is a good representation of the data. If this is not the case you may better off using some form of nonlinear model. So, one of the first things you want to do when looking at your data is to assess if a straight line represents a reasonable summary for it. Let’s go back to the first simple model we explored and plot the smoothed conditional means</p>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## Warning in geom_line(data = BCS0708, aes(x = round(tcarea/0.1) * 0.1, y =
## tcviolent), : Ignoring unknown parameters: `fun.y`</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 3664 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 3664 rows containing non-finite values (`stat_summary()`).</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()`</code></pre>
<pre><code>## Warning: Removed 3664 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Is the straight line a good summary? One way of exploring this when you only have one predictor is to use a <a href="http://en.wikipedia.org/wiki/Local_regression">Loess regression line</a>. This form of local regression subsets chunks of data around your X axis to try to estimate a regression line that fits well a region of the data. These are the blue lines that you see plotted in the residual plots earlier. This visualisation posted online in the wonderful Simply Statistics blog.</p>
<p><img src="imgs/SSblog.gif" /></p>
<div class="sourceCode" id="cb647"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb647-1"><a href="regression-in-the-real-world.html#cb647-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> BCS0708, <span class="fu">aes</span>(<span class="at">x =</span> tcarea, <span class="at">y =</span> tcviolent)) <span class="sc">+</span></span>
<span id="cb647-2"><a href="regression-in-the-real-world.html#cb647-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>, <span class="at">position =</span> <span class="st">&quot;jitter&quot;</span>, <span class="at">color =</span><span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb647-3"><a href="regression-in-the-real-world.html#cb647-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb647-4"><a href="regression-in-the-real-world.html#cb647-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb647-5"><a href="regression-in-the-real-world.html#cb647-5" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 3664 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula = &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Removed 3664 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 3664 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>We already knew from the residual plots we had a problem here, but hopefully this plots also helps you to see the problem more clearly. This plot seems to suggest that perhaps the relationship here is somehow curvilinear, although notice that the curvature takes place as the result of the underprediction in the regions of X with sparser data.</p>
<div id="using-polynomial-regression" class="section level4 hasAnchor" number="9.4.0.1">
<h4><span class="header-section-number">9.4.0.1</span> Using polynomial regression<a href="regression-in-the-real-world.html#using-polynomial-regression" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>What do you do in a situation such as this? There are a number of solutions, some of which are more complex than others. One fairly simple way of extending the linear model is by using polynomial regression. Essentially what this does is to incorporate a transformed predictor into the model with the intention of capturing the curvature apparent in the data. What we do is that we add additional terms to the model until we are satisfied we capture the pattern in the data.</p>
<p>So say we are working with a simple model of <code>tcviolent ~ tcarea</code>. We could try to fit a polynomial regression adding a second term with a squared <code>tcarea</code>. This would produce the following predicted line:</p>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="regression-in-the-real-world.html#cb653-1" tabindex="-1"></a><span class="co">#Notice the arguments in the first geom_smooth(). We are asking ggplot to produce a linear model using the specified formula. This formula asks for a polynomial regression with a quadratic term added (that&#39;s why you see the 2). You may want to look at the help files for the poly() function, which is one of the ways of inserting polynomials in a R formula (the preferred way of doing it if you want to have more than a quadratic term).</span></span>
<span id="cb653-2"><a href="regression-in-the-real-world.html#cb653-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> BCS0708, <span class="fu">aes</span>(<span class="at">x =</span> tcarea, <span class="at">y =</span> tcviolent)) <span class="sc">+</span></span>
<span id="cb653-3"><a href="regression-in-the-real-world.html#cb653-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>, <span class="at">position =</span> <span class="st">&quot;jitter&quot;</span>, <span class="at">color =</span><span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb653-4"><a href="regression-in-the-real-world.html#cb653-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb653-5"><a href="regression-in-the-real-world.html#cb653-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb653-6"><a href="regression-in-the-real-world.html#cb653-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 3664 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula = &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Removed 3664 rows containing non-finite values (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 3664 rows containing missing values (`geom_point()`).</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Essentially, adding this extra term allows the possibility of increasing slopes with <code>tcarea</code> and helps to model U-shaped patterns. If we still think that the non-linearities are not adequately captured we could try with a cubic transformation (raising to the power of 3) and adding this additional term. The more complex your polynomial, the more difficult may be to interpret your tabular results.</p>
<p>Another thing to note is that the higher order polyomial you add, the better your model fits. <strong>However</strong> that doesn’t necessarily mean that it is a better model. You might venture into what is known as overfitting, where your model fits your data greatly, but uses its predictive power. See this <a href="http://www.nature.com/nmeth/journal/v13/n9/full/nmeth.3968.html">paper by Lever et al. in Nature</a> to learn more.</p>
<p>Let’s return to the more complex model we were examining and rerun the model with a quadratic term added. When including quadratic terms as part of a formula in R we need to use the <code>I()</code>function for converting objects (or the <code>poly()</code> function).</p>
<div class="sourceCode" id="cb658"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb658-1"><a href="regression-in-the-real-world.html#cb658-1" tabindex="-1"></a>fit_3q <span class="ot">&lt;-</span> <span class="fu">lm</span>(tcviolent <span class="sc">~</span> tcarea <span class="sc">+</span> <span class="fu">I</span>(tcarea<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> sex, <span class="at">data =</span> BCS0708)</span>
<span id="cb658-2"><a href="regression-in-the-real-world.html#cb658-2" tabindex="-1"></a><span class="fu">summary</span>(fit_3q )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = tcviolent ~ tcarea + I(tcarea^2) + sex, data = BCS0708)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.6267 -0.5840 -0.1253  0.4740  4.2919 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.265422   0.015870  16.725  &lt; 2e-16 ***
## tcarea       0.273647   0.011811  23.169  &lt; 2e-16 ***
## I(tcarea^2)  0.047727   0.007628   6.257 4.12e-10 ***
## sexmale     -0.592218   0.020238 -29.263  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9037 on 8008 degrees of freedom
##   (3664 observations deleted due to missingness)
## Multiple R-squared:  0.1852, Adjusted R-squared:  0.1849 
## F-statistic: 606.8 on 3 and 8008 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The near-zero p-value associated with the quadratic term suggests that it leads to an improved model. We can use the <code>anova()</code> function to quantify the improvement in the model.</p>
<div class="sourceCode" id="cb660"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb660-1"><a href="regression-in-the-real-world.html#cb660-1" tabindex="-1"></a><span class="fu">anova</span>(fit_3, fit_3q)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: tcviolent ~ tcarea + sex
## Model 2: tcviolent ~ tcarea + I(tcarea^2) + sex
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1   8009 6572.4                                  
## 2   8008 6540.4  1    31.976 39.151 4.123e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the output the first model is the one without the quadratic term (the straight line model) and the second model is the one with the added polynomial. What the <code>anova()</code> function is doing here is to run a hypothesis test that the two models fit the data equally well, whereas the research hypothesis is that the model with the quadratic term represents a better fit. The p value we observe is virtually zero. So clearly in this case adding a quadratic term represents an improvement to our model. If we compare the plot of the residuals against the fitted values we can see that the non-linear pattern that was evident in our simpler model washes away once we introduce the quadratic term.</p>
<div class="sourceCode" id="cb662"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb662-1"><a href="regression-in-the-real-world.html#cb662-1" tabindex="-1"></a><span class="co">#You would use this code to obtain only the fitted against the residuals.</span></span>
<span id="cb662-2"><a href="regression-in-the-real-world.html#cb662-2" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_3, <span class="sc">~</span><span class="dv">1</span>, <span class="at">fitted =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)    
## Tukey test    4.6065        4.094e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb664"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb664-1"><a href="regression-in-the-real-world.html#cb664-1" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_3q, <span class="sc">~</span><span class="dv">1</span>, <span class="at">fitted =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-16-2.png" width="672" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)
## Tukey test    1.2223           0.2216</code></pre>
<div class="sourceCode" id="cb666"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb666-1"><a href="regression-in-the-real-world.html#cb666-1" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_3q)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-16-3.png" width="672" /></p>
<pre><code>##             Test stat Pr(&gt;|Test stat|)  
## tcarea        -0.3529          0.72420  
## I(tcarea^2)    1.8972          0.05783 .
## sex                                     
## Tukey test     1.2223          0.22159  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can run the tests we used before to check for fit:</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="regression-in-the-real-world.html#cb668-1" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_3q, <span class="at">plot =</span> <span class="cn">FALSE</span>) <span class="co">#Setting the plot argument to false will only print the tests.</span></span></code></pre></div>
<pre><code>##             Test stat Pr(&gt;|Test stat|)  
## tcarea        -0.3529          0.72420  
## I(tcarea^2)    1.8972          0.05783 .
## sex                                     
## Tukey test     1.2223          0.22159  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see that the tests are no longer significant. Should we add a cubic term? The Loess line was not a simple curve, would a more complex model be required?</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb670-1"><a href="regression-in-the-real-world.html#cb670-1" tabindex="-1"></a>fit_3c <span class="ot">&lt;-</span> <span class="fu">lm</span>(tcviolent <span class="sc">~</span> tcarea <span class="sc">+</span> <span class="fu">I</span>(tcarea<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(tcarea<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> sex, <span class="at">data =</span> BCS0708)</span>
<span id="cb670-2"><a href="regression-in-the-real-world.html#cb670-2" tabindex="-1"></a><span class="fu">summary</span>(fit_3c)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = tcviolent ~ tcarea + I(tcarea^2) + I(tcarea^3) + 
##     sex, data = BCS0708)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7352 -0.5846 -0.1276  0.4733  4.2846 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.272535   0.017115  15.924  &lt; 2e-16 ***
## tcarea       0.263588   0.014888  17.705  &lt; 2e-16 ***
## I(tcarea^2)  0.035936   0.013078   2.748  0.00601 ** 
## I(tcarea^3)  0.005696   0.005132   1.110  0.26708    
## sexmale     -0.591906   0.020239 -29.245  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9037 on 8007 degrees of freedom
##   (3664 observations deleted due to missingness)
## Multiple R-squared:  0.1853, Adjusted R-squared:  0.1849 
## F-statistic: 455.4 on 4 and 8007 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In this case, we have less evidence that adding this additional term would improve the fit. As you can see the p value associated with the cubic term is not significant.</p>
<p>As we discussed when introducing regression interpreting the coefficients can get tricky. That is certainly the case when you add polynomial regression. The description of results in this case will typically focus on the general pattern of results, rather than in the regression coefficients for your transformed variable. One solution to this is to produce graphical displays of the relationship such as those that can be obtained with the <code>effects</code> package.</p>
<div class="sourceCode" id="cb672"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb672-1"><a href="regression-in-the-real-world.html#cb672-1" tabindex="-1"></a><span class="fu">library</span>(effects)</span></code></pre></div>
<pre><code>## lattice theme set by effectsTheme()
## See ?effectsTheme for details.</code></pre>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="regression-in-the-real-world.html#cb674-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(fit_3q)<span class="sc">$</span>tcarea)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>We have discussed transforming the variable by squaring it, but other curvilinear patterns may require other transformations such as taking the inverse (1/X), when there is a decreasing negative effect of the predictor on the response variable, or taking the square root of X, when there is a dminishing positive impact of the predictor on the response variable -refer to <a href="http://link.springer.com/book/10.1007%2F978-1-4614-9170-5">Weisburt and Britt, 2014: 516-518</a>. There are also other more sophisticated ways of accommodating non linearities -by means of fitting regression splines or using generalised additive models. But those models are well beyond the scope of this course.</p>
</div>
</div>
<div id="transformations-and-unequal-variance" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Transformations and unequal variance<a href="regression-in-the-real-world.html#transformations-and-unequal-variance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You may have noticed in the residual plot for our polynomial regression that the variance does not seem constant in this case. Again, there are a number of solutions one could apply in this type of scenarios. One possibility is to replace the usual coefficient standard errors with standard errors that will be consistent even with heterokedasticity.</p>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb675-1"><a href="regression-in-the-real-world.html#cb675-1" tabindex="-1"></a><span class="fu">library</span>(lmtest, <span class="at">quietly =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb678-1"><a href="regression-in-the-real-world.html#cb678-1" tabindex="-1"></a><span class="fu">library</span>(arm, <span class="at">quietly =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## arm (Version 1.13-1, built: 2022-8-25)</code></pre>
<pre><code>## Working directory is /Users/eonkim/Desktop/R/CrimeSciData</code></pre>
<pre><code>## 
## Attaching package: &#39;arm&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     logit</code></pre>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="regression-in-the-real-world.html#cb683-1" tabindex="-1"></a><span class="fu">coeftest</span>(fit_3q, <span class="at">vcov =</span> hccm)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)  0.2654218  0.0170871  15.5334 &lt; 2.2e-16 ***
## tcarea       0.2736472  0.0120168  22.7721 &lt; 2.2e-16 ***
## I(tcarea^2)  0.0477268  0.0087201   5.4732 4.553e-08 ***
## sexmale     -0.5922181  0.0200261 -29.5724 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="regression-in-the-real-world.html#cb685-1" tabindex="-1"></a><span class="fu">display</span>(fit_3q, <span class="at">digit=</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## lm(formula = tcviolent ~ tcarea + I(tcarea^2) + sex, data = BCS0708)
##             coef.est coef.se
## (Intercept)  0.2654   0.0159
## tcarea       0.2736   0.0118
## I(tcarea^2)  0.0477   0.0076
## sexmale     -0.5922   0.0202
## ---
## n = 8012, k = 4
## residual sd = 0.9037, R-Squared = 0.19</code></pre>
<p>You will see the standard errors are marginally larger but nothing else changes in this case.</p>
<!--

```r
library(car)
BCS0708$fearviol <-BCS0708$tcviolent+3
BCS0708$asbperc <-BCS0708$tcarea+3
symbox(~fearviol, data=BCS0708)
```

<img src="09-regression2_files/figure-html/unnamed-chunk-21-1.png" width="672" />

```r
symbox(~asbperc, data=BCS0708)
```

<img src="09-regression2_files/figure-html/unnamed-chunk-21-2.png" width="672" />
-->
<p>Let’s look at another example using the <code>Boston</code> dataset. We will model crime as a linear function of property values (<code>medv</code>), lower status of the population (<code>lstat</code>), distances to employment centres (<code>dis</code>), and a binary input indicating proximity to the river (<code>chas</code>).</p>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="regression-in-the-real-world.html#cb687-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb687-2"><a href="regression-in-the-real-world.html#cb687-2" tabindex="-1"></a>fit_B1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(crim <span class="sc">~</span> medv <span class="sc">+</span> lstat <span class="sc">+</span> dis <span class="sc">+</span> chas, <span class="at">data =</span> Boston)</span>
<span id="cb687-3"><a href="regression-in-the-real-world.html#cb687-3" tabindex="-1"></a><span class="fu">summary</span>(fit_B1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = crim ~ medv + lstat + dis + chas, data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -12.030  -3.104  -1.102   1.686  79.947 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  7.49610    2.43009   3.085 0.002150 ** 
## medv        -0.15261    0.05545  -2.752 0.006130 ** 
## lstat        0.26042    0.07851   3.317 0.000976 ***
## dis         -0.96116    0.18657  -5.152 3.72e-07 ***
## chas        -1.31968    1.34461  -0.981 0.326842    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.462 on 501 degrees of freedom
## Multiple R-squared:  0.2534, Adjusted R-squared:  0.2474 
## F-statistic: 42.51 on 4 and 501 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We see that the R square is not too bad at .24 and three of the inputs are significantly associated with crime in the direction one would expect. Areas with more expensive properties and closer to employment centres tend to have less crime, and areas with a greater proportion of lower status residents tend to have more crime. Let’s have a look at the residuals.</p>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="regression-in-the-real-world.html#cb689-1" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_B1)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)    
## medv          9.8302        &lt; 2.2e-16 ***
## lstat         4.8810        1.422e-06 ***
## dis           5.7387        1.655e-08 ***
## chas          0.3195           0.7495    
## Tukey test   10.2705        &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see non-linearities and quite obvious unequal variances.</p>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="regression-in-the-real-world.html#cb691-1" tabindex="-1"></a><span class="fu">qqPlot</span>(fit_B1)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre><code>## [1] 381 419</code></pre>
<p>The qqplot shows a clear skew in the residuals. And if we were to look at outliers we would also see problems.</p>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb693-1"><a href="regression-in-the-real-world.html#cb693-1" tabindex="-1"></a><span class="fu">outlierTest</span>(fit_B1)</span></code></pre></div>
<pre><code>##      rstudent unadjusted p-value Bonferroni p
## 381 12.261038         2.1183e-30   1.0719e-27
## 419  9.272410         5.4493e-19   2.7573e-16
## 406  8.096815         4.3344e-15   2.1932e-12
## 411  6.252293         8.6804e-10   4.3923e-07
## 415  4.331682         1.7891e-05   9.0527e-03
## 428  4.081649         5.2049e-05   2.6337e-02
## 405  4.068951         5.4871e-05   2.7765e-02</code></pre>
<p>Quite a few of the outliers are significant and the influence plot shows further evidence of it:</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb695-1"><a href="regression-in-the-real-world.html#cb695-1" tabindex="-1"></a><span class="fu">influencePlot</span>(fit_B1)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre><code>##        StudRes         Hat       CookD
## 284  0.8641468 0.045088797 0.007055541
## 373  1.1682560 0.049768556 0.014286161
## 381 12.2610377 0.008840861 0.206603429
## 406  8.0968152 0.010238469 0.120149835
## 419  9.2724104 0.007275786 0.107751496</code></pre>
<p>What this analysis shows is that often problems come together and are related to each other. If you remember from week 2, the distribution of crime is highly skewed. In these cases it can make sense to transform the Y variable as a first step, since this skew is surely playing a role in the unequal spread that we see in the residual plots.</p>
<p>We can use the <code>symbox()</code> function to investigate what transformation will make <code>crim</code> less skewed.</p>
<div class="sourceCode" id="cb697"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb697-1"><a href="regression-in-the-real-world.html#cb697-1" tabindex="-1"></a><span class="fu">symbox</span>(<span class="sc">~</span>crim, <span class="at">data=</span>Boston)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>This set of boxplots suggests what the distribution of <code>crim</code> would look like if we were to apply different transformations. In this case, as in many other instances with skewed distributions, applying the logarithmic transformation seems the most appropriate one. Let’s explore the implications of it:</p>
<div class="sourceCode" id="cb698"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb698-1"><a href="regression-in-the-real-world.html#cb698-1" tabindex="-1"></a>fit_B2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(crim) <span class="sc">~</span> medv <span class="sc">+</span> lstat <span class="sc">+</span> dis <span class="sc">+</span> chas, <span class="at">data =</span> Boston)</span>
<span id="cb698-2"><a href="regression-in-the-real-world.html#cb698-2" tabindex="-1"></a><span class="fu">summary</span>(fit_B2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(crim) ~ medv + lstat + dis + chas, data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.6978 -1.0714  0.0511  1.0719  3.8100 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.70156    0.45774   1.533  0.12599    
## medv        -0.02745    0.01044  -2.629  0.00883 ** 
## lstat        0.08746    0.01479   5.914 6.17e-09 ***
## dis         -0.52131    0.03514 -14.834  &lt; 2e-16 ***
## chas         0.12079    0.25328   0.477  0.63364    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.406 on 501 degrees of freedom
## Multiple R-squared:  0.5807, Adjusted R-squared:  0.5774 
## F-statistic: 173.5 on 4 and 501 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>You will notice that the coefficients change in magnitude, since we have re-expressed the response variable in the logarithmic scale, but the direction and the statistical significance remain unchanged. The R square, however, is now much better. Let’s look at the residuals:</p>
<div class="sourceCode" id="cb700"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb700-1"><a href="regression-in-the-real-world.html#cb700-1" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_B2)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<pre><code>##            Test stat Pr(&gt;|Test stat|)    
## medv          8.0190        7.613e-15 ***
## lstat         0.4771           0.6335    
## dis           7.7327        5.838e-14 ***
## chas          0.2330           0.8158    
## Tukey test    6.0272        1.668e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see that the non-constant variance is still present, though to a lesser degree, and we can now also see that the non-linearities persist. We can further investigate this model using a scatterplot matrix. In fact, this should typically preceed fitting the model to assess potential non-linearities. We will use the <code>scatterplotMatrix</code> of the <code>car</code> package.</p>
<div class="sourceCode" id="cb702"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb702-1"><a href="regression-in-the-real-world.html#cb702-1" tabindex="-1"></a><span class="fu">scatterplotMatrix</span>(<span class="sc">~</span> <span class="fu">log</span>(crim) <span class="sc">+</span> medv <span class="sc">+</span> lstat <span class="sc">+</span> dis <span class="sc">+</span> chas, <span class="at">data=</span>Boston)</span></code></pre></div>
<pre><code>## Warning in smoother(x[subs], y[subs], col = smoother.args$col[i], log.x =
## FALSE, : could not fit smooth

## Warning in smoother(x[subs], y[subs], col = smoother.args$col[i], log.x =
## FALSE, : could not fit smooth

## Warning in smoother(x[subs], y[subs], col = smoother.args$col[i], log.x =
## FALSE, : could not fit smooth

## Warning in smoother(x[subs], y[subs], col = smoother.args$col[i], log.x =
## FALSE, : could not fit smooth</code></pre>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>The matrix reveals that the distribution of the nummerical predictors are all also suffering from some skew and display a curvilinear relationship with the response variable.</p>
<div class="sourceCode" id="cb704"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb704-1"><a href="regression-in-the-real-world.html#cb704-1" tabindex="-1"></a>fit_B3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(crim) <span class="sc">~</span> <span class="fu">poly</span>(medv, <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">log</span>(lstat) <span class="sc">+</span> <span class="fu">log</span>(dis) <span class="sc">+</span> chas, <span class="at">data =</span> Boston)</span>
<span id="cb704-2"><a href="regression-in-the-real-world.html#cb704-2" tabindex="-1"></a><span class="fu">summary</span>(fit_B3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(crim) ~ poly(medv, 2) + log(lstat) + log(dis) + 
##     chas, data = Boston)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5307 -0.9095  0.1236  0.8464  3.2641 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      1.1206     0.5491   2.041   0.0418 *  
## poly(medv, 2)1 -11.9003     2.3688  -5.024 7.07e-07 ***
## poly(medv, 2)2  10.8617     1.4738   7.370 7.11e-13 ***
## log(lstat)       0.2556     0.1923   1.329   0.1843    
## log(dis)        -2.1193     0.1398 -15.156  &lt; 2e-16 ***
## chas             0.1537     0.2297   0.669   0.5035    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.274 on 500 degrees of freedom
## Multiple R-squared:  0.656,  Adjusted R-squared:  0.6526 
## F-statistic: 190.7 on 5 and 500 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Transforming the <code>lstat</code> and <code>dis</code> variable in the logarithmic scale<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a> and allowing a quadratic term for median property value seems to increase the R square and improve the fit of the model.</p>
<div class="sourceCode" id="cb706"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb706-1"><a href="regression-in-the-real-world.html#cb706-1" tabindex="-1"></a><span class="fu">residualPlots</span>(fit_B3)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre><code>##               Test stat Pr(&gt;|Test stat|)  
## poly(medv, 2)                             
## log(lstat)       0.5714          0.56801  
## log(dis)         1.9410          0.05282 .
## chas             0.3017          0.76303  
## Tukey test       1.1169          0.26402  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Although we still have some issues with unequal spread, the outputs do not lead us to alter our substantive conclusions.</p>
<div class="sourceCode" id="cb708"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb708-1"><a href="regression-in-the-real-world.html#cb708-1" tabindex="-1"></a><span class="fu">coeftest</span>(fit_B3, <span class="at">vcov =</span> hccm) <span class="co">#The vcov is providing a covariance matrix that is corrected for heteroskedasticity.</span></span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                 Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)      1.12062    0.54230   2.0664    0.0393 *  
## poly(medv, 2)1 -11.90029    2.43779  -4.8816 1.418e-06 ***
## poly(medv, 2)2  10.86169    1.61947   6.7069 5.390e-11 ***
## log(lstat)       0.25564    0.19310   1.3238    0.1862    
## log(dis)        -2.11930    0.13050 -16.2402 &lt; 2.2e-16 ***
## chas             0.15374    0.20064   0.7663    0.4439    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As you can see it is more productive “to make a model fit step by step (e.g., transformation estimation) than to postulate a simple model and find out what went wrong” (Harrell, 2001: ix). It is an iterative process that requires practice.</p>
</div>
<div id="boostrapping-regression-models" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> Boostrapping regression models<a href="regression-in-the-real-world.html#boostrapping-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we discussed in previous sessions, bootstrapping is an approach to statistical inference that is based on building a “resampling” distribution from the observed sample. This approach allow us to obtain distribution-free confidence intervals and some of the bootstrap approaches are also helpful when other assumptions of the model are violated. For more details about this topic you may want to read Fox and Weisber (2012) <a href="http://socserv.mcmaster.ca/jfox/Books/Companion/appendix/Appendix-Bootstrapping.pdf">online appendix</a>. Here we are going to illustrated boostrapping with observation resampling.</p>
<p>We can use the <code>Boot()</code> function that comes with the <code>car</code> package for this.</p>
<div class="sourceCode" id="cb710"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb710-1"><a href="regression-in-the-real-world.html#cb710-1" tabindex="-1"></a>fit_B3_boot <span class="ot">&lt;-</span> <span class="fu">Boot</span>(fit_B3, <span class="at">f=</span>coef, <span class="at">R=</span><span class="dv">999</span>, <span class="at">method=</span><span class="st">&quot;case&quot;</span>) <span class="co">#This will take our latest model for the Boston data, will run 999 resamples of the cases, and will resample the coefficients (you could resample other quantitites)</span></span>
<span id="cb710-2"><a href="regression-in-the-real-world.html#cb710-2" tabindex="-1"></a><span class="fu">summary</span>(fit_B3_boot)</span></code></pre></div>
<pre><code>## 
## Number of bootstrap replications R = 999 
##                 original   bootBias  bootSE   bootMed
## (Intercept)      1.12062 -0.0103797 0.54260   1.10022
## poly(medv, 2)1 -11.90029 -0.0137443 2.38281 -11.83298
## poly(medv, 2)2  10.86169  0.0650774 1.60768  10.94070
## log(lstat)       0.25564  0.0022354 0.19166   0.26229
## log(dis)        -2.11930  0.0049542 0.12834  -2.11582
## chas             0.15374  0.0010373 0.19310   0.15380</code></pre>
<p>The summary gives the original sample value for each component of the bootstrapped statistics, along with the bootstrap estimates of bias, the difference between the average bootstrapped
value of the statistic and its original-sample value. The bootstrap estimates of standard error are computed as the standard deviation of the bootstrap replicates.</p>
<p>Confidence intervals using various methods can be applied to this object:</p>
<div class="sourceCode" id="cb712"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb712-1"><a href="regression-in-the-real-world.html#cb712-1" tabindex="-1"></a><span class="fu">confint</span>(fit_B3_boot)</span></code></pre></div>
<pre><code>## Bootstrap bca confidence intervals
## 
##                       2.5 %     97.5 %
## (Intercept)      0.01353137  2.1183307
## poly(medv, 2)1 -16.42654988 -7.3626855
## poly(medv, 2)2   7.57298828 13.9793073
## log(lstat)      -0.11032319  0.6372392
## log(dis)        -2.37733389 -1.8784905
## chas            -0.22771982  0.5404902</code></pre>
</div>
<div id="multicollinearity" class="section level2 hasAnchor" number="9.7">
<h2><span class="header-section-number">9.7</span> Multicollinearity<a href="regression-in-the-real-world.html#multicollinearity" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The regression model may experience some problems where there is strong collinearity, when the predictors are related among themselves. In these scenarios, the standard errors for the coefficients will be large and the confidence intervals will also be broader. The power of the hypothesis test for our t statistic will be lower. That is, it will be more difficult to detect a significant relationship even if there is one.</p>
<p>To diagnose multicollinearity a first step may be to observe the correlation between the predictors in the model. Let’s first subset the data to only obtain the relevant predictors and our main outcome. For this I will introduce another form of selecting columns in a dataframe using the <code>dplyr</code> package.</p>
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb714-1"><a href="regression-in-the-real-world.html#cb714-1" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">quietly=</span><span class="cn">TRUE</span>, <span class="at">warn.conflict=</span><span class="cn">FALSE</span>)</span>
<span id="cb714-2"><a href="regression-in-the-real-world.html#cb714-2" tabindex="-1"></a>Boston_R <span class="ot">&lt;-</span> <span class="fu">select</span>(Boston, crim, lstat, dis, chas, medv)</span></code></pre></div>
<p>Then we can obtain the correlations using the <code>cor()</code> function.</p>
<div class="sourceCode" id="cb715"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb715-1"><a href="regression-in-the-real-world.html#cb715-1" tabindex="-1"></a>c_1 <span class="ot">&lt;-</span> <span class="fu">cor</span>(Boston_R)</span>
<span id="cb715-2"><a href="regression-in-the-real-world.html#cb715-2" tabindex="-1"></a>c_1</span></code></pre></div>
<pre><code>##              crim      lstat         dis        chas       medv
## crim   1.00000000  0.4556215 -0.37967009 -0.05589158 -0.3883046
## lstat  0.45562148  1.0000000 -0.49699583 -0.05392930 -0.7376627
## dis   -0.37967009 -0.4969958  1.00000000 -0.09917578  0.2499287
## chas  -0.05589158 -0.0539293 -0.09917578  1.00000000  0.1752602
## medv  -0.38830461 -0.7376627  0.24992873  0.17526018  1.0000000</code></pre>
<p>And then we can visualise these correlations with the <code>corrplot</code> package.</p>
<div class="sourceCode" id="cb717"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb717-1"><a href="regression-in-the-real-world.html#cb717-1" tabindex="-1"></a><span class="fu">library</span>(corrplot, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## corrplot 0.92 loaded</code></pre>
<div class="sourceCode" id="cb719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb719-1"><a href="regression-in-the-real-world.html#cb719-1" tabindex="-1"></a><span class="fu">corrplot</span>(c_1, <span class="at">order =</span> <span class="st">&quot;hclust&quot;</span>, <span class="at">tl.pos=</span><span class="st">&quot;d&quot;</span>)</span></code></pre></div>
<p><img src="09-regression2_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>We can see that there are some non-trivial correlations between some of the predictors, in particular between median property value and percent lower status (r=-73). And keep in mind these coefficients are not picking up well enough the actual curvilinear relation that we saw in the scatterplot matrix printed earlier.</p>
<p>Correlations among pairs of variables, will only give you a first impression of the problem. What we are really concerned is what happens once you throw all the variables in the model. Not all problems with multicollinearity will be detected by the correlation matrix. The recommended reading describes the variance inflation factor as a tool to diagnose multicollinearity. Let’s look at the on we obtain with the first model (pre-transformations) that we run with the <code>Boston</code> dataset:</p>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb720-1"><a href="regression-in-the-real-world.html#cb720-1" tabindex="-1"></a><span class="fu">vif</span>(fit_B1)</span></code></pre></div>
<pre><code>##     medv    lstat      dis     chas 
## 2.358517 2.850675 1.399747 1.057865</code></pre>
<p>Typically a VIF larger than 5 or 10 indicates serious problems wiht collinearity. Fox (2008) recommends using the square root of the variance inflation factor:</p>
<div class="sourceCode" id="cb722"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb722-1"><a href="regression-in-the-real-world.html#cb722-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">vif</span>(fit_B1))</span></code></pre></div>
<pre><code>##     medv    lstat      dis     chas 
## 1.535746 1.688394 1.183109 1.028525</code></pre>
<p>Typically, it is assumed that you need a value greater than 2 for the square root of the variance inflation factor before collinearity seriously impairs the precision of the estimation. It does not look as if we would have to worry much on the basis of these results.</p>
<p>When you have a set of related inputs or regressors (either because you have a multicategory factor and various dummy variables or because you have polynomial regressors) you cannot use the variance inflation factor. There is, however, a similar statistics that you can use in these contexts: the <strong>generalised variance inflation factor</strong>. We could use this measure for the final model we used for the <code>Boston</code> data. We invoke this statistic using the same code as before:</p>
<div class="sourceCode" id="cb724"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb724-1"><a href="regression-in-the-real-world.html#cb724-1" tabindex="-1"></a><span class="fu">vif</span>(fit_B3)</span></code></pre></div>
<pre><code>##                   GVIF Df GVIF^(1/(2*Df))
## poly(medv, 2) 4.439803  2        1.451580
## log(lstat)    4.151409  1        2.037501
## log(dis)      1.770096  1        1.330450
## chas          1.058015  1        1.028599</code></pre>
<p>Now that we are using the transformed variables it looks as if we have more of an issue with the coefficient for <code>lstat</code>. The confidence interval for this coefficient is about 2 times larger than it would be without collinearity, which goes a long way towards explaining why it is not longer significant.</p>
<p>The problem with collinear inputs is that they do not add much new to the model. Non-collinearity is not an assumption of the regression model. And everything is related to everything else, to some extent at least. But if a predictor is strongly related to some other input, then we are simply adding redundant information to the model. If you are developing a risk assessment tool for probation, you don’t want to add loads of predictors that are highly correlated (for this simply is requiring probation to collect redundant information). Also, in these situations is hard to tell apart the relative importance of the collinear predictors (if you are interested in explanation rather than prediction). It can be difficult to separate their effects.</p>
<p>There are a number of proposed solutions to multicollinearity, from dropping the culprits to creating composite variables that summarise variation among the correlated inputs, to more complex techniques, but all these are well beyond the aims of this course.</p>
<p>It is very important, however, to remember that there are some circunstances in which multicollinearity can be safely ignored. Professor Paul Allison <a href="http://www.statisticalhorizons.com/multicollinearity">discusses this issue</a> in his blog and you may want to check the full discussion. Essentially, Prof. Allison argues that one can ignore multicollinearity when:</p>
<ul>
<li><p>“The variables with high VIFs are control variables, and the variables of interest do not have high VIFs… In this case the coefficients of the variables of interest are not affected, and the performance of the control variables as controls is not impaired.”</p></li>
<li><p>“The high VIFs are caused by the inclusion of powers or products of other variables. If you specify a regression model with both x and x2, there’s a good chance that those two variables will be highly correlated. Similarly, if your model has x, z, and xz, both x and z are likely to be highly correlated with their product. This is not something to be concerned about, however, because the p-value for xz is not affected by the multicollinearity…”</p></li>
<li><p>“The variables with high VIFs are indicator (dummy) variables that represent a categorical variable with three or more categories. If the proportion of cases in the reference category is small, the indicator variables will necessarily have high VIFs, even if the categorical variable is not associated with other variables in the regression model.”</p></li>
</ul>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="14">
<li id="fn14"><p>“If the log transformation is applied to an input variable as well as the outcome the coefficient can be interpreted as the expected proportional change in Y per proportional chance in X” (Gelman and Hill, 2007). I strongly recommend you read <a href="https://stats.oarc.ucla.edu/sas/faq/how-can-i-interpret-log-transformed-variables-in-terms-of-percent-change-in-linear-regression/">this</a> for further aid in interpreting coefficients when you have used log transformations.<a href="regression-in-the-real-world.html#fnref14" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="an-introduction-to-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
